<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-A15AP0F" name="Validation" tests="2" failures="2" timestamp="28 Feb 2021 14:45:11 GMT" time="11.047" errors="0">
  <testcase name="calling" time="0.202" classname="PracticeDemo.validateTest">
    <failure type="java.lang.AssertionError" message="expected [Featured Courses12] but found [Featured Courses]">
      <![CDATA[java.lang.AssertionError: expected [Featured Courses12] but found [Featured Courses]
	at PracticeDemo.validateTest.calling(validateTest.java:46)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- calling -->
  <testcase name="calling" time="0.233" classname="PracticeDemo.validateTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at PracticeDemo.BasicPageDemo.getScreenshot(BasicPageDemo.java:83)
	at PracticeDemo.Listeners.onTestFailure(Listeners.java:33)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- calling -->
</testsuite> <!-- Validation -->
